namespace ObsInterop;

public enum gs_shader_param_type
{
    GS_SHADER_PARAM_UNKNOWN,
    GS_SHADER_PARAM_BOOL,
    GS_SHADER_PARAM_FLOAT,
    GS_SHADER_PARAM_INT,
    GS_SHADER_PARAM_STRING,
    GS_SHADER_PARAM_VEC2,
    GS_SHADER_PARAM_VEC3,
    GS_SHADER_PARAM_VEC4,
    GS_SHADER_PARAM_INT2,
    GS_SHADER_PARAM_INT3,
    GS_SHADER_PARAM_INT4,
    GS_SHADER_PARAM_MATRIX4X4,
    GS_SHADER_PARAM_TEXTURE,
}
