namespace ObsInterop;

public enum obs_deinterlace_mode
{
    OBS_DEINTERLACE_MODE_DISABLE,
    OBS_DEINTERLACE_MODE_DISCARD,
    OBS_DEINTERLACE_MODE_RETRO,
    OBS_DEINTERLACE_MODE_BLEND,
    OBS_DEINTERLACE_MODE_BLEND_2X,
    OBS_DEINTERLACE_MODE_LINEAR,
    OBS_DEINTERLACE_MODE_LINEAR_2X,
    OBS_DEINTERLACE_MODE_YADIF,
    OBS_DEINTERLACE_MODE_YADIF_2X,
}
